const API='/api/cpt_recursos';
const state={token:localStorage.getItem('cpt_token'),campaigns:[],selected:null,quantities:{},view:'dashboard'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const isoToday=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const res=await fetch(API+path,{...options,headers});if(res.status===204)return null;const body=await res.json().catch(()=>({}));if(!res.ok){if(res.status===401&&state.token){localStorage.removeItem('cpt_token');state.token=null}throw new Error(body.detail||'Não foi possível concluir a operação')}return body}
function show(id){['#clientArea','#authArea','#managerApp'].forEach(s=>$(s).classList.toggle('hidden',s!==id))}
async function setMode(mode){$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='cliente'){show('#clientArea');await loadCampaigns();const slug=location.hash.slice(1);if(slug&&slug!=='cliente'&&slug!=='gestor')openCampaign(slug)}else if(state.token){openManager()}else{show('#authArea');prepareAuth()}}
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));

async function loadCampaigns(){try{state.campaigns=await api('/public/campanhas');$('#campaignGrid').innerHTML=state.campaigns.length?state.campaigns.map(c=>`<article class="campaign-card"><span class="campaign-icon">◎</span><h3>${esc(c.nome)}</h3><p>${esc(c.descricao||'Participe desta campanha e ajude a transformar uma ideia em resultado.')}</p><button data-slug="${esc(c.slug)}">Ver ${c.produtos} produto${c.produtos===1?'':'s'} →</button></article>`).join(''):'<div class="empty">Ainda não há campanhas ativas.</div>';$$('[data-slug]').forEach(b=>b.onclick=()=>openCampaign(b.dataset.slug))}catch(e){$('#campaignGrid').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function openCampaign(slug){try{state.selected=await api('/public/campanhas/'+encodeURIComponent(slug));history.replaceState(null,'','#'+slug);state.quantities={};$('#campaignGrid').classList.add('hidden');$('#backCampaigns').classList.remove('hidden');$('#clientTitle').textContent=state.selected.nome;renderOrder()}catch(e){toast(e.message)}}
function renderOrder(success){
  const box=$('#orderExperience');box.classList.remove('hidden');
  if(success){box.innerHTML=`<div class="success-card"><b>✓</b><h2>Pedido recebido!</h2><p>Anote o número <strong>#${success.id}</strong>. A situação inicial do pagamento é pendente.</p><button class="primary" id="newOrder">Fazer outro pedido</button></div>`;$('#newOrder').onclick=()=>{state.quantities={};renderOrder()};return}
  const products=state.selected.produtos||[],pix=state.selected.chave_pix||'';
  box.innerHTML=`<div class="order-layout"><section class="panel"><h3>Escolha seus produtos</h3><div class="product-list">${products.length?products.map(p=>`<article class="product"><div><h4>${esc(p.nome)}</h4><p>${esc(p.descricao)} · <b>${money(p.preco)}</b></p></div><div class="qty"><button data-minus="${p.id}">−</button><b id="qty${p.id}">0</b><button data-plus="${p.id}">+</button></div></article>`).join(''):'<div class="empty">Nenhum produto disponível.</div>'}</div></section><form id="orderForm" class="order-form"><h3>Dados para coleta</h3><label>Nome do cliente<input name="cliente_nome" required minlength="2" autocomplete="name" placeholder="Seu nome completo"></label><label><span>Data para coleta <em id="todayHint" class="today-hint">Hoje</em></span><input id="collectionDate" name="data_coleta" type="date" value="${isoToday()}" required></label><label>Descrição do pedido personalizado<textarea name="observacoes" maxlength="1000" rows="3" placeholder="Ex.: sem cebola, cor azul, embalagem para presente..."></textarea></label>${pix?`<div class="pix-box"><small>CHAVE PIX</small><span>${esc(pix)}</span><button type="button" id="copyPix">Copiar chave Pix</button></div>`:''}<div class="total"><span>Total</span><b id="orderTotal">${money(0)}</b></div><p class="error" id="orderError"></p><button class="primary wide" ${products.length?'':'disabled'}>Confirmar pedido</button></form></div>`;
  $$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.plus,1));$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.minus,-1));$('#orderForm').onsubmit=submitOrder;
  $('#collectionDate').onchange=e=>$('#todayHint').classList.toggle('hidden',e.target.value!==isoToday());
  if(pix)$('#copyPix').onclick=()=>copyText(pix);
}
function changeQty(id,delta){state.quantities[id]=Math.max(0,(state.quantities[id]||0)+delta);$('#qty'+id).textContent=state.quantities[id];const total=state.selected.produtos.reduce((n,p)=>n+Number(p.preco)*(state.quantities[p.id]||0),0);$('#orderTotal').textContent=money(total)}
async function copyText(value){try{await navigator.clipboard.writeText(value);toast('Chave Pix copiada')}catch{const input=document.createElement('textarea');input.value=value;document.body.appendChild(input);input.select();document.execCommand('copy');input.remove();toast('Chave Pix copiada')}}
async function submitOrder(e){e.preventDefault();const itens=Object.entries(state.quantities).filter(([,q])=>q>0).map(([produto_id,quantidade])=>({produto_id:+produto_id,quantidade}));if(!itens.length){$('#orderError').textContent='Escolha ao menos um produto.';return}const fd=new FormData(e.target);try{const result=await api('/public/pedidos',{method:'POST',body:JSON.stringify({campanha_id:state.selected.id,cliente_nome:fd.get('cliente_nome'),data_coleta:fd.get('data_coleta'),observacoes:fd.get('observacoes'),itens})});renderOrder(result)}catch(err){$('#orderError').textContent=err.message}}
$('#backCampaigns').onclick=()=>{history.replaceState(null,'','#cliente');$('#campaignGrid').classList.remove('hidden');$('#orderExperience').classList.add('hidden');$('#backCampaigns').classList.add('hidden');$('#clientTitle').textContent='O que você quer apoiar hoje?'};

async function prepareAuth(){try{const s=await api('/auth/status');const setup=!s.configurado;$('#setupName').classList.toggle('hidden',!setup);$('#authTitle').textContent=setup?'Crie o primeiro acesso':'Acesse sua conta';$('#authHint').textContent=setup?'Cadastre o responsável principal para começar.':'Use os dados do responsável pela captação.';$('#authForm').dataset.setup=setup?'1':'0'}catch(e){$('#authError').textContent=e.message}}
$('#authForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),setup=e.target.dataset.setup==='1';const payload={login:f.get('login'),senha:f.get('senha')};if(setup)payload.nome=f.get('nome');try{const r=await api(setup?'/auth/setup':'/auth/login',{method:'POST',body:JSON.stringify(payload)});state.token=r.token;localStorage.setItem('cpt_token',r.token);openManager()}catch(err){$('#authError').textContent=err.message}};
$('#logout').onclick=()=>{localStorage.removeItem('cpt_token');state.token=null;setMode('gestor')};
async function openManager(){show('#managerApp');$('#managerDate').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});await managerView(state.view)}
$$('[data-view]').forEach(b=>b.onclick=()=>managerView(b.dataset.view));$('#refresh').onclick=()=>managerView(state.view);
async function managerView(view){state.view=view;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={dashboard:'Visão geral',pedidos:'Pedidos do dia',campanhas:'Campanhas',equipe:'Equipe',relatorio:'Relatório de vendas',configuracoes:'Configurações'};$('#viewTitle').textContent=titles[view];$('#managerContent').innerHTML='<div class="loading">Atualizando dados…</div>';try{await ({dashboard:renderDashboard,pedidos:renderOrders,campanhas:renderCampaigns,equipe:renderTeam,relatorio:renderReport,configuracoes:renderSettings}[view])()}catch(e){$('#managerContent').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function renderDashboard(){const [d,o]=await Promise.all([api('/dashboard'),api('/pedidos')]);const max=Math.max(Number(d.hoje.total),Number(d.dia_anterior.total),1);$('#managerContent').innerHTML=`<section class="metric-grid"><article class="metric"><small>PEDIDOS HOJE</small><b>${d.hoje.pedidos}</b></article><article class="metric"><small>VENDAS HOJE</small><b>${money(d.hoje.total)}</b></article><article class="metric"><small>RECEBIDO</small><b>${money(d.hoje.pago)}</b></article><article class="metric"><small>PENDENTE</small><b>${money(d.hoje.pendente)}</b></article></section><section class="manager-grid"><article class="panel"><div class="panel-head"><h3>Pedidos para hoje</h3><button class="link" data-jump="pedidos">Ver todos</button></div>${ordersHtml(o.slice(0,6))}</article><article class="panel"><div class="panel-head"><h3>Comparativo diário</h3><span class="badge ${d.variacao_percentual>=0?'pago':'pendente'}">${d.variacao_percentual==null?'Sem base':`${d.variacao_percentual>=0?'+':''}${d.variacao_percentual.toFixed(1)}%`}</span></div><div class="comparison"><div class="bar" style="height:${Number(d.dia_anterior.total)/max*100}%"><span>Anterior</span></div><div class="bar today" style="height:${Number(d.hoje.total)/max*100}%"><span>Hoje</span></div></div></article></section>`;$('[data-jump]').onclick=()=>managerView('pedidos');bindPayments()}
function ordersHtml(rows){return `<div class="orders">${rows.length?rows.map(o=>`<div class="order-row"><div><b>${esc(o.cliente_nome)}</b><small>#${o.id} · ${esc(o.campanha_nome||o.campanha||'')} · ${(o.itens||[]).map(i=>`${i.quantidade}× ${esc(i.nome)}`).join(', ')}</small>${o.observacoes?`<p class="order-note">“${esc(o.observacoes)}”</p>`:''}</div><div><b>${money(o.valor_total)}</b><span class="badge ${o.status_pagamento}">${o.status_pagamento}</span></div><button class="pay-btn" data-pay="${o.id}" data-status="${o.status_pagamento}">${o.status_pagamento==='pago'?'Marcar pendente':'Marcar pago'}</button></div>`).join(''):'<div class="empty">Nenhum pedido para esta data.</div>'}</div>`}
function bindPayments(){$$('[data-pay]').forEach(b=>b.onclick=async()=>{try{await api(`/pedidos/${b.dataset.pay}/pagamento`,{method:'PATCH',body:JSON.stringify({status:b.dataset.status==='pago'?'pendente':'pago'})});toast('Pagamento atualizado');managerView(state.view)}catch(e){toast(e.message)}})}
async function renderOrders(){const rows=await api('/pedidos');$('#managerContent').innerHTML=`<article class="panel"><div class="toolbar"><b>Coletas de ${new Date().toLocaleDateString('pt-BR')}</b><input id="orderDate" type="date" value="${isoToday()}"></div><div id="orderRows">${ordersHtml(rows)}</div></article>`;bindPayments();$('#orderDate').onchange=async e=>{const list=await api('/pedidos?data_coleta='+e.target.value);$('#orderRows').innerHTML=ordersHtml(list);bindPayments()}}
async function renderCampaigns(){const rows=await api('/campanhas');state.campaigns=rows;$('#managerContent').innerHTML=`<section class="manager-grid"><article class="panel"><div class="panel-head"><h3>Suas campanhas</h3></div><div class="cards">${rows.length?rows.map(c=>`<div class="mini-card"><h4>${esc(c.nome)}</h4><p>${esc(c.descricao||'Sem descrição')}</p><div class="actions"><span class="badge ${c.ativa?'pago':'pendente'}">${c.ativa?'Ativa':'Inativa'}</span><button class="link" data-product="${c.id}">Produtos</button></div><small>Link: /cpt_recursos#${esc(c.slug)}</small></div>`).join(''):'<div class="empty">Crie sua primeira campanha.</div>'}</div></article><form id="campaignForm" class="panel form-grid"><h3 class="full">Nova campanha</h3><label class="full">Nome<input name="nome" required minlength="3"></label><label class="full">Descrição<textarea name="descricao" rows="3"></textarea></label><label class="full">Chave Pix<input name="chave_pix"></label><button class="primary full">Criar campanha</button></form></section>`;$('#campaignForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{await api('/campanhas',{method:'POST',body:JSON.stringify({...f,ativa:true})});toast('Campanha criada');renderCampaigns()}catch(err){toast(err.message)}};$$('[data-product]').forEach(b=>b.onclick=()=>renderProducts(+b.dataset.product))}
async function renderProducts(id){const rows=await api(`/campanhas/${id}/produtos`),campaign=state.campaigns.find(c=>c.id===id);$('#managerContent').innerHTML=`<button class="link" id="backAdmin">← Campanhas</button><section class="manager-grid"><article class="panel"><h3>Produtos de ${esc(campaign.nome)}</h3><div class="cards">${rows.length?rows.map(p=>`<div class="mini-card"><h4>${esc(p.nome)}</h4><p>${esc(p.descricao)}</p><b>${money(p.preco)}</b></div>`).join(''):'<div class="empty">Nenhum produto cadastrado.</div>'}</div></article><form id="productForm" class="panel form-grid"><h3 class="full">Novo produto</h3><label class="full">Nome<input name="nome" required></label><label class="full">Descrição<input name="descricao"></label><label>Preço<input name="preco" type="number" min="0.01" step="0.01" required></label><button class="primary full">Adicionar produto</button></form></section>`;$('#backAdmin').onclick=renderCampaigns;$('#productForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{await api(`/campanhas/${id}/produtos`,{method:'POST',body:JSON.stringify({...f,preco:Number(f.preco),ativo:true})});toast('Produto adicionado');renderProducts(id)}catch(err){toast(err.message)}}}
async function renderTeam(){const rows=await api('/equipe');$('#managerContent').innerHTML=`<section class="manager-grid"><article class="panel"><h3>Integrantes</h3><div class="cards">${rows.length?rows.map(m=>`<div class="mini-card"><h4>${esc(m.nome)}</h4><span class="badge ${m.vigente?'pago':'pendente'}">${m.tipo==='oficial'?'Oficial':m.vigente?'Temporário ativo':'Período encerrado'}</span>${m.fim_em?`<p>Na equipe até ${new Date(m.fim_em+'T12:00').toLocaleDateString('pt-BR')}</p>`:''}<button class="link" data-remove="${m.id}">Remover</button></div>`).join(''):'<div class="empty">Nenhum integrante cadastrado.</div>'}</div></article><form id="teamForm" class="panel form-grid"><h3 class="full">Adicionar integrante</h3><label class="full">Nome<input name="nome" required></label><label>Vínculo<select name="tipo"><option value="oficial">Oficial</option><option value="temporario">Temporário</option></select></label><label>Início<input name="inicio_em" type="date" value="${isoToday()}" required></label><label class="full" id="endLabel">Fim (obrigatório para temporário)<input name="fim_em" type="date"></label><button class="primary full">Adicionar à equipe</button></form></section>`;$('#teamForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(!f.fim_em)f.fim_em=null;try{await api('/equipe',{method:'POST',body:JSON.stringify(f)});toast('Integrante adicionado');renderTeam()}catch(err){toast(err.message)}};$$('[data-remove]').forEach(b=>b.onclick=async()=>{if(confirm('Remover este integrante da equipe?')){await api('/equipe/'+b.dataset.remove,{method:'DELETE'});renderTeam()}})}
async function renderReport(){const r=await api('/relatorios/ultimas-24h');$('#managerContent').innerHTML=`<section class="metric-grid"><article class="metric"><small>PEDIDOS EM 24H</small><b>${r.quantidade}</b></article><article class="metric"><small>VALOR TOTAL</small><b>${money(r.total)}</b></article></section><article class="panel" style="margin-top:18px"><div class="panel-head"><h3>Últimas 24 horas</h3><button class="secondary" id="csv" ${r.quantidade?'':'disabled'}>Baixar CSV</button></div>${ordersHtml(r.pedidos)}</article>`;if(r.quantidade)$('#csv').onclick=()=>downloadCsv(r.pedidos)}
function downloadCsv(rows){const cells=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv=['Pedido,Cliente,Campanha,Coleta,Descrição personalizada,Status,Valor,Criado em',...rows.map(r=>[r.id,r.cliente_nome,r.campanha,r.data_coleta,r.observacoes,r.status_pagamento,r.valor_total,r.criado_em].map(cells).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=`captacao-24h-${isoToday()}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function renderSettings(){const u=await api('/me');$('#managerContent').innerHTML=`<form id="settingsForm" class="panel form-grid" style="max-width:650px"><h3 class="full">Dados do responsável</h3><label class="full">Nome<input name="nome" value="${esc(u.nome)}" required></label><label class="full">Chave Pix<input name="chave_pix" value="${esc(u.chave_pix)}"></label><label class="full">Login<input value="${esc(u.login)}" disabled></label><button class="primary full">Salvar alterações</button></form>`;$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{await api('/me',{method:'PUT',body:JSON.stringify(f)});toast('Dados salvos')}catch(err){toast(err.message)}}}
setInterval(()=>{if(state.token&&!$('#managerApp').classList.contains('hidden')&&(state.view==='dashboard'||state.view==='pedidos'))managerView(state.view)},120000);
if(location.hash==='#gestor')setMode('gestor');else setMode('cliente');
