const API='/api/fornecedores',state={token:localStorage.getItem('frn_token'),rows:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(API+path,{...opt,headers});if(r.status===204)return null;const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||'Não foi possível concluir');return b}
async function start(){if(state.token){$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');load()}else{try{const s=await api('/auth/status');$('#authForm').dataset.setup=s.configurado?'0':'1';$('#nameField').classList.toggle('hidden',s.configurado);$('#authTitle').textContent=s.configurado?'Entrar':'Criar acesso inicial'}catch(e){$('#authError').textContent=e.message}}}
$('#authForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),setup=e.target.dataset.setup==='1';if(!setup)delete f.nome;try{const r=await api(setup?'/auth/setup':'/auth/login',{method:'POST',body:JSON.stringify(f)});state.token=r.token;localStorage.setItem('frn_token',r.token);start()}catch(err){$('#authError').textContent=err.message}};
$('#logout').onclick=()=>{localStorage.removeItem('frn_token');location.reload()};
async function load(search=''){try{state.rows=await api('?busca='+encodeURIComponent(search));$('#count').textContent=`${state.rows.length} fornecedor${state.rows.length===1?'':'es'}`;$('#supplierGrid').innerHTML=state.rows.length?state.rows.map(card).join(''):'<div class="empty">Nenhum fornecedor encontrado.</div>';bind()}catch(e){if(e.message.includes('Sessão')){$('#logout').click()}else toast(e.message)}}
function card(s){return `<article class="card"><h3>${esc(s.nome)}</h3><p>${esc(s.documento||'Documento não informado')}</p><dl><div><dt>CONTATO</dt><dd>${esc(s.contato||'—')}</dd></div><div><dt>TELEFONE / E-MAIL</dt><dd>${esc(s.telefone||'—')} ${s.email?'· '+esc(s.email):''}</dd></div><div><dt>CHAVE PIX</dt><dd>${esc(s.chave_pix||'—')}</dd></div></dl><div class="actions"><button data-edit="${s.id}">Editar</button><button class="delete" data-delete="${s.id}">Remover</button></div></article>`}
function bind(){$$('[data-edit]').forEach(b=>b.onclick=()=>openModal(state.rows.find(s=>s.id===+b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Deseja remover este fornecedor?')){try{await api('/cadastros/'+b.dataset.delete,{method:'DELETE'});toast('Fornecedor removido');load($('#search').value)}catch(e){toast(e.message)}}})}
function openModal(s={}){const f=$('#supplierForm');f.reset();Object.entries(s).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??''});$('#modalTitle').textContent=s.id?'Editar fornecedor':'Novo fornecedor';$('#formError').textContent='';$('#modal').showModal()}
$('#newSupplier').onclick=()=>openModal();$('#close').onclick=()=>$('#modal').close();
$('#supplierForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),id=data.id;delete data.id;try{await api(id?'/cadastros/'+id:'',{method:id?'PUT':'POST',body:JSON.stringify(data)});$('#modal').close();toast(id?'Fornecedor atualizado':'Fornecedor cadastrado');load($('#search').value)}catch(err){$('#formError').textContent=err.message}};
let timer;$('#search').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>load(e.target.value),300)};start();
