const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={token:sessionStorage.getItem('clari_token'),dashboard:null,transactions:[],trips:[],reserves:[],filter:'todos'};
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=v=>new Date(v+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'});
const icons=()=>window.lucide?.createIcons({attrs:{'aria-hidden':'true'}});
const api=async(path,opts={})=>{const r=await fetch('/api/financeiro'+path,{...opts,headers:{'Content-Type':'application/json',...(state.token?{Authorization:'Bearer '+state.token}:{}),...(opts.headers||{})}});if(r.status===401&&path!='/login'){logout();throw Error('Sessão expirada')}const data=await r.json();if(!r.ok)throw Error(data.detail||'Não foi possível concluir');return data};
$('#today').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const data=Object.fromEntries(new FormData(e.currentTarget));try{const res=await api('/login',{method:'POST',body:JSON.stringify(data)});state.token=res.token;sessionStorage.setItem('clari_token',res.token);showApp()}catch(err){$('#loginError').textContent=err.message}});
function logout(){sessionStorage.removeItem('clari_token');state.token=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}
$('#logout').onclick=logout;
async function showApp(){ $('#login').classList.add('hidden');$('#app').classList.remove('hidden');icons();await refresh() }
async function refresh(){try{[state.dashboard,state.transactions,state.trips,state.reserves]=await Promise.all([api('/dashboard'),api('/lancamentos'),api('/viagens'),api('/reservas')]);renderDashboard();renderTransactions();renderTrips();renderReserves()}catch(e){toast(e.message)}}
function renderDashboard(){const d=state.dashboard;$('#balance').textContent=money(d.saldo);$('#income').textContent=money(d.receitas);$('#expense').textContent=money(d.despesas);$('#pending').textContent=money(d.pendente);$('#fixed').textContent=money(d.fixos);$('#balanceHint').textContent=d.saldo>=0?'Seu saldo está positivo. Continue assim.':'Atenção: suas despesas superam as receitas.';renderRows($('#recentList'),d.recentes.slice(0,5),false);const max=Math.max(1,...d.mensal.flatMap(m=>[m.receitas,m.despesas]));$('#flowChart').innerHTML=d.mensal.length?d.mensal.map(m=>`<div class="bar-group"><i class="bar in" style="height:${m.receitas/max*88}%"></i><i class="bar out" style="height:${m.despesas/max*88}%"></i><span class="bar-label">${m.mes.slice(5)}</span></div>`).join(''):'<div class="empty">Adicione lançamentos para visualizar o gráfico</div>';const total=d.categorias.reduce((s,c)=>s+c.valor,0)||1;$('#categoryList').innerHTML=d.categorias.length?d.categorias.map(c=>`<div class="category"><span>${c.categoria}</span><b>${money(c.valor)}</b><div class="progress"><i style="width:${c.valor/total*100}%"></i></div></div>`).join(''):'<div class="empty">Nenhum gasto cadastrado</div>'}
function renderRows(el,rows,canDelete=true){el.innerHTML=rows.length?rows.map(t=>`<div class="transaction-row"><span class="tx-icon ${t.natureza}"><i data-lucide="${t.natureza==='receita'?'arrow-down-left':'arrow-up-right'}"></i></span><div><b>${esc(t.descricao)}</b><small>${esc(t.categoria)} · ${esc(t.modalidade)} · ${date(t.data_vencimento)}</small></div><b class="amount ${t.natureza}">${t.natureza==='despesa'?'−':'+'} ${money(t.valor)}</b>${canDelete?`<button class="delete-btn" data-delete="${t.id}" title="Excluir"><i data-lucide="trash-2"></i></button>`:''}</div>`).join(''):'<div class="empty">Nenhum lançamento por aqui ainda.</div>';icons()}
function renderTransactions(){const rows=state.transactions.filter(t=>state.filter==='todos'||t.natureza===state.filter||t.status===state.filter);renderRows($('#transactionList'),rows)}
function renderTrips(){const el=$('#tripList');el.innerHTML=state.trips.length?state.trips.map(t=>{const p=Math.min(100,t.orcamento?t.gasto/t.orcamento*100:0);return `<article class="trip-card"><span class="eyebrow">${esc(t.status)}</span><h3>${esc(t.nome)}</h3><p>${esc(t.destino)} · ${date(t.data_inicio)}</p><div class="trip-meta"><span>Gasto ${money(t.gasto)}</span><b>${money(t.orcamento)}</b></div><div class="progress"><i style="width:${p}%;background:${p>90?'#e98568':'#1f6b59'}"></i></div><div class="card-actions"><button class="secondary icon-button" data-trip-expense="${t.id}"><i data-lucide="plus"></i>Adicionar gasto</button><button class="danger-icon" data-delete-trip="${t.id}" aria-label="Excluir planejamento" title="Excluir planejamento"><i data-lucide="trash-2"></i></button></div></article>`}).join(''):'<div class="panel empty">Crie seu primeiro planejamento de viagem.</div>';icons()}
function renderReserves(){const el=$('#reserveList');el.innerHTML=state.reserves.length?state.reserves.map(r=>{const p=Math.min(100,r.meta?r.guardado/r.meta*100:0);return `<article class="reserve-card"><div class="reserve-top"><span class="reserve-icon ${r.tipo}"><i data-lucide="${r.tipo==='emergencia'?'shield-check':'lock-keyhole'}"></i></span><span class="reserve-type">${r.tipo==='emergencia'?'Reserva de emergência':'Fundo de garantia'}</span></div><h3>${esc(r.nome)}</h3><div class="reserve-values"><div><small>GUARDADO</small><b>${money(r.guardado)}</b></div><div><small>META</small><b>${money(r.meta)}</b></div></div><div class="progress"><i style="width:${p}%"></i></div><div class="reserve-foot"><span>${p.toFixed(0)}% concluído</span>${r.prazo?`<span>até ${date(r.prazo)}</span>`:''}</div><div class="card-actions"><button class="secondary icon-button" data-reserve-deposit="${r.id}"><i data-lucide="circle-dollar-sign"></i>Guardar dinheiro</button><button class="danger-icon" data-delete-reserve="${r.id}" aria-label="Excluir reserva" title="Excluir reserva"><i data-lucide="trash-2"></i></button></div></article>`}).join(''):'<div class="panel empty reserve-empty"><i data-lucide="shield-plus"></i><b>Crie sua primeira reserva</b><span>Comece aos poucos e fortaleça sua segurança financeira.</span></div>';icons()}
function navigate(view){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===view));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$('#pageTitle').textContent={dashboard:'Visão geral',lancamentos:'Lançamentos',viagens:'Planejamentos',relatorios:'Relatórios'}[view];window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view]');if(nav)navigate(nav.dataset.view);const go=e.target.closest('[data-go]');if(go)navigate(go.dataset.go);const open=e.target.closest('[data-open]');if(open)openModal(open.dataset.open);const filter=e.target.closest('[data-filter]');if(filter){state.filter=filter.dataset.filter;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b===filter));renderTransactions()}const del=e.target.closest('[data-delete]');if(del&&confirm('Excluir este lançamento?')){await api('/lancamentos/'+del.dataset.delete,{method:'DELETE'});toast('Lançamento excluído');refresh()}const exp=e.target.closest('[data-trip-expense]');if(exp)openModal('tripExpense',exp.dataset.tripExpense);const deposit=e.target.closest('[data-reserve-deposit]');if(deposit)openModal('reserveDeposit',deposit.dataset.reserveDeposit);const delTrip=e.target.closest('[data-delete-trip]');if(delTrip&&confirm('Excluir este planejamento e todos os gastos vinculados?')){await api('/viagens/'+delTrip.dataset.deleteTrip,{method:'DELETE'});toast('Planejamento excluído');refresh()}const delReserve=e.target.closest('[data-delete-reserve]');if(delReserve&&confirm('Excluir esta reserva e todo o histórico de aportes?')){await api('/reservas/'+delReserve.dataset.deleteReserve,{method:'DELETE'});toast('Reserva excluída');refresh()}});
const today=()=>new Date().toISOString().slice(0,10);
function openModal(type,id){
  const fields=$('#modalFields'); $('#modalForm').dataset.type=type; $('#modalForm').dataset.id=id||'';
  const configs={
    transaction:['NOVO REGISTRO','Adicionar lançamento',`<label class="full">Descrição<input name="descricao" required placeholder="Ex.: Aluguel, salário..."></label><label>Natureza<select name="natureza"><option value="despesa">Despesa</option><option value="receita">Receita</option></select></label><label>Valor<input name="valor" type="number" step="0.01" min="0" required placeholder="0,00"></label><label>Modalidade<select name="modalidade"><option value="fixo">Gasto fixo</option><option value="variavel">Gasto variável</option><option value="assinatura">Assinatura</option><option value="parcelado">Parcelado</option><option value="eventual">Eventual</option></select></label><label>Categoria<select name="categoria"><option>Moradia</option><option>Alimentação</option><option>Transporte</option><option>Saúde</option><option>Lazer</option><option>Educação</option><option>Assinaturas</option><option>Outros</option></select></label><label>Vencimento<input name="data_vencimento" type="date" value="${today()}" required></label><label>Status<select name="status"><option value="pago">Pago</option><option value="pendente">Pendente</option></select></label><label class="full">Observação<textarea name="observacao" rows="2" placeholder="Opcional"></textarea></label>`],
    trip:['NOVO PLANEJAMENTO','Planejar viagem',`<label class="full">Nome do plano<input name="nome" required placeholder="Ex.: Férias em Floripa"></label><label class="full">Destino<input name="destino" required placeholder="Cidade ou roteiro"></label><label>Data de início<input name="data_inicio" type="date" value="${today()}" required></label><label>Data final<input name="data_fim" type="date" value="${today()}" required></label><label>Orçamento<input name="orcamento" type="number" step="0.01" min="0" required></label><label>Status<select name="status"><option value="planejada">Planejada</option><option value="confirmada">Confirmada</option><option value="concluida">Concluída</option></select></label>`],
    tripExpense:['GASTO DA VIAGEM','Adicionar gasto',`<label class="full">Descrição<input name="descricao" required placeholder="Ex.: Hotel, passagem..."></label><label>Categoria<select name="categoria"><option>Hospedagem</option><option>Transporte</option><option>Alimentação</option><option>Passeios</option><option>Compras</option><option>Outros</option></select></label><label>Valor<input name="valor" type="number" step="0.01" min="0" required></label><label>Data<input name="data" type="date" value="${today()}" required></label>`],
    reserve:['NOVA RESERVA','Criar objetivo de segurança',`<label class="full">Nome da reserva<input name="nome" required placeholder="Ex.: Reserva familiar"></label><label>Finalidade<select name="tipo"><option value="emergencia">Emergência</option><option value="garantia">Garantia e segurança</option></select></label><label>Meta financeira<input name="meta" type="number" step="0.01" min="1" required placeholder="0,00"></label><label>Prazo opcional<input name="prazo" type="date"></label><label class="full">Observação<textarea name="observacao" rows="2" placeholder="Para que esta reserva será usada?"></textarea></label>`],
    reserveDeposit:['NOVO APORTE','Guardar dinheiro',`<label>Valor do aporte<input name="valor" type="number" step="0.01" min="0.01" required placeholder="0,00"></label><label>Data<input name="data" type="date" value="${today()}" required></label><label class="full">Observação<textarea name="observacao" rows="2" placeholder="Opcional"></textarea></label>`]
  };
  const cfg=configs[type]; $('#modalEyebrow').textContent=cfg[0]; $('#modalTitle').textContent=cfg[1]; fields.innerHTML=cfg[2]; $('#formError').textContent=''; $('#modal').showModal();
}
$('#closeModal').onclick=()=>$('#modal').close();
$('#modalForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const type=e.currentTarget.dataset.type;try{let path='/lancamentos';if(type==='trip')path='/viagens';if(type==='tripExpense')path='/viagens/'+e.currentTarget.dataset.id+'/gastos';if(type==='reserve')path='/reservas';if(type==='reserveDeposit')path='/reservas/'+e.currentTarget.dataset.id+'/aportes';await api(path,{method:'POST',body:JSON.stringify(f)});$('#modal').close();toast(type==='reserveDeposit'?'Dinheiro guardado com sucesso':'Salvo com sucesso');await refresh()}catch(err){$('#formError').textContent=err.message}});
$('#downloadPdf').onclick=()=>{const d=state.dashboard;$('#printReport').innerHTML=`<h1>Relatório financeiro cleeFinanças</h1><p>Gerado em ${new Date().toLocaleDateString('pt-BR')}</p><div class="print-summary"><div><small>Saldo</small><b>${money(d.saldo)}</b></div><div><small>Receitas</small><b>${money(d.receitas)}</b></div><div><small>Despesas</small><b>${money(d.despesas)}</b></div><div><small>A pagar</small><b>${money(d.pendente)}</b></div></div><h2>Lançamentos</h2><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Modalidade</th><th>Status</th><th>Valor</th></tr></thead><tbody>${state.transactions.map(t=>`<tr><td>${date(t.data_vencimento)}</td><td>${esc(t.descricao)}</td><td>${esc(t.categoria)}</td><td>${esc(t.modalidade)}</td><td>${esc(t.status)}</td><td>${t.natureza==='despesa'?'- ':'+ '}${money(t.valor)}</td></tr>`).join('')}</tbody></table>`;window.print()};
function esc(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
icons();
if(state.token)showApp();
